# docker-compose.yml
version: "3.9"

services:
  sideger-backend:
    image: sideger-backend:v1.0.0
    container_name: sideger-backend
    network_mode: "host"
    # ports:
    #   - "8000:8000"
    volumes:
      - ./src-backend/sidegerapp.db:/app/sidegerapp.db
      - ~/.ssh:/root/.ssh:ro
      - ./src-backend:/app
    env_file:
      - ./src-backend/.env
    # environment:
      # override temporalmente:
      # - DATABASE_URL=sqlite:///./sidegerapp.db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8000/"]
      interval: 30s
      timeout: 3s
      retries: 3
